### ISSUE TITLE
Config -> Extract From Templates

### ISSUE THREAD

**Issue by Egis-Moshe** [egis/support-portal#40]
http://egis.papertrail.co.za/wiki/Imaging/Setup%20extract%20from%20templates

http://egis.papertrail.co.za/wiki/Configuration/Setting%20up%20extractFromTemplates

**Comment by pkarthikr** [comment]
Fixed in https://github.com/egis/support-portal/pull/48

**Comment by Egis-Moshe** [comment]
These need to be merged
